### ISSUE TITLE
Use a PHP framework?

### ISSUE THREAD

**Issue by mcallan83** [hjbotha/twain#1]
Just came across this project from a post on Reddit. I have been playing around with Traefik and mentally mapped out how to build my own auth server to work with Traefik's forward authentication feature. I haven't started coding anything yet, but your project works almost exactly like I planned on mine working. I am glad you found a working solution!

My question is... do you have any plans to convert this to using a PHP framework? I think Lumen would be a good choice for this. It has support for databases, sending mail, and an easy to use router. It is also pretty well known in the PHP community, has built in support for unit tests, and would probably reduce the actual amount of code you have to write.

My plan was to use Lumen, and then build a docker image so anyone can include this auth server into their Traefik setup really quickly. I was just curious what your plans were with this project before I started my own considering they would really be doing the same thing.

**Comment by hjbotha** [comment]
Heya. I have no such plans, so go for it! Feel free to reuse anything in Twain too if you think it'll help.

**Comment by mcallan83** [comment]
Ok cool. I'll be sure to shoot you over a link if and when I get something built :)
